version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./Dataset:/app/Dataset
    environment:
      - PYTHONUNBUFFERED=1
    # Ensures the container restarts if it crashes, but not if you stop it manually
    restart: unless-stopped
